defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  dist:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - README.md
            - LICENSE
  compile: 
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn compile
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - es
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn ci
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm publish

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - dist:
          requires:
            - test
          filters:
            branches:
              only: deploy
      - compile:
          requires:
            - test
          filters:
            branches:
              only: deploy
      - publish:
          requires:
            - dist
            - compile
